"""add cameras, parking_spots, occupancy_state, occupancy_events, pipeline_runs

Revision ID: b8c2326ff8b5
Revises:
Create Date: 2026-09-02 10:44:40.434858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8c2326ff8b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_uri", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=False),
        sa.Column("sample_fps", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parking_spots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spot_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parking_spots_camera_id"), "parking_spots", ["camera_id"], unique=False
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("frames_processed", sa.Integer(), nullable=False),
        sa.Column("avg_latency_ms", sa.Float(), nullable=True),
        sa.Column("p95_latency_ms", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_camera_id"), "pipeline_runs", ["camera_id"], unique=False
    )
    op.create_table(
        "occupancy_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column("is_occupied", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["parking_spots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_occupancy_events_occurred_at"), "occupancy_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_occupancy_events_spot_id"), "occupancy_events", ["spot_id"], unique=False
    )
    op.create_table(
        "occupancy_state",
        sa.Column("spot_id", sa.Integer(), nullable=False),
        sa.Column("is_occupied", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["spot_id"],
            ["parking_spots.id"],
        ),
        sa.PrimaryKeyConstraint("spot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("occupancy_state")
    op.drop_index(op.f("ix_occupancy_events_spot_id"), table_name="occupancy_events")
    op.drop_index(op.f("ix_occupancy_events_occurred_at"), table_name="occupancy_events")
    op.drop_table("occupancy_events")
    op.drop_index(op.f("ix_pipeline_runs_camera_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_parking_spots_camera_id"), table_name="parking_spots")
    op.drop_table("parking_spots")
    op.drop_table("cameras")
    # ### end Alembic commands ###
